package pmi2024;

import ingenieros.Ingeniero;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Comparator;
import javax.swing.JOptionPane;
import javax.swing.JSpinner.DateEditor;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import proyectos.DesarrolloDeHardware;
import proyectos.DesarrolloDeSoftware;
import proyectos.ProyectoTecnologico;

public class GUI extends javax.swing.JFrame {

    private DefaultTableModel modeloTablaProyectos;
    private ArrayList<Ingeniero> arrayIngenieros;
    private ArrayList<ProyectoTecnologico> arrayProyectos;
    private TableRowSorter<TableModel> ordenadorTablaPresupuesto;

    /**
     * Creates new form OrganizadorDeProyectos
     *
     * @param arrayIngenieros
     * @param arrayProyectos
     */
    public GUI(ArrayList<Ingeniero> arrayIngenieros, ArrayList<ProyectoTecnologico> arrayProyectos) {

        initComponents();
        this.arrayIngenieros = arrayIngenieros;
        this.arrayProyectos = arrayProyectos;

        String[] columnas = {"Nombre", "Tipo", "Descripcion", "Inicio", "Fin", "Presupuesto"};
        modeloTablaProyectos = new DefaultTableModel(columnas, 0);
        tablaProyectos.setModel(modeloTablaProyectos);

        ordenadorTablaPresupuesto = new TableRowSorter<>(modeloTablaProyectos);
        ordenadorTablaPresupuesto.setComparator(5, Comparator.naturalOrder());

        tablaProyectos.setRowSorter(ordenadorTablaPresupuesto);

        spinnerFechaInicio.setEditor(new DateEditor(spinnerFechaInicio, "dd/MM/yyyy"));
        spinnerFechaFin.setEditor(new DateEditor(spinnerFechaFin, "dd/MM/yyyy"));

        buttonGroupTipoProyecto.add(radioHardware);
        buttonGroupTipoProyecto.add(radioSoftware);
        buttonGroupTipoProyecto.add(radioHardware1);
        buttonGroupTipoProyecto.add(radioSoftware1);

        setIconImage(Toolkit.getDefaultToolkit().getImage("icon.png")); // totalmente innecesario pero mira que lindo queda!
        setTitle("Organizador de Proyectos");
        textTitulo.setText("MENU PRINCIPAL");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTipoProyecto = new javax.swing.ButtonGroup();
        PanelTitulo = new javax.swing.JPanel();
        textTitulo = new javax.swing.JLabel();
        contenedor = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        botonProyectos = new javax.swing.JButton();
        botonIngenieros = new javax.swing.JButton();
        botonRecursos = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        panelProyectos = new javax.swing.JPanel();
        subpanelPrincipalProyectos = new javax.swing.JPanel();
        scrollTablaProyectos = new javax.swing.JScrollPane();
        tablaProyectos = new javax.swing.JTable();
        botonVolverAlMenu = new javax.swing.JButton();
        botonAgregarProyecto = new javax.swing.JButton();
        botonModificarProyecto = new javax.swing.JButton();
        botonEliminarProyecto = new javax.swing.JButton();
        textCantProyectos = new javax.swing.JLabel();
        textCantProyectosHardware = new javax.swing.JLabel();
        textCantProyectosSoftware = new javax.swing.JLabel();
        subpanelCargarProyecto = new javax.swing.JPanel();
        campoProyectoTitulo = new javax.swing.JTextField();
        campoProyectoDescripcion = new javax.swing.JTextField();
        campoProyectoTipo = new javax.swing.JTextField();
        spinnerProyectoPresupuesto = new javax.swing.JSpinner();
        spinnerFechaInicio = new javax.swing.JSpinner();
        spinnerFechaFin = new javax.swing.JSpinner();
        radioHardware = new javax.swing.JRadioButton();
        radioSoftware = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botonCargarProyecto = new javax.swing.JButton();
        botonVolverPanelPrincipalProyectos = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        subpanelModProyectos = new javax.swing.JPanel();
        campoProyectoTitulo1 = new javax.swing.JTextField();
        campoProyectoDescripcion1 = new javax.swing.JTextField();
        campoProyectoTipo1 = new javax.swing.JTextField();
        spinnerProyectoPresupuesto1 = new javax.swing.JSpinner();
        spinnerProyectoFechaInicio1 = new javax.swing.JSpinner();
        spinnerProyectoFechaFin1 = new javax.swing.JSpinner();
        radioHardware1 = new javax.swing.JRadioButton();
        radioSoftware1 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        botonCargarProyecto1 = new javax.swing.JButton();
        botonVolverPanelPrincipalProyectos1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelTitulo.setBackground(new java.awt.Color(153, 153, 255));

        textTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        textTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textTitulo.setText("Titulo");

        javax.swing.GroupLayout PanelTituloLayout = new javax.swing.GroupLayout(PanelTitulo);
        PanelTitulo.setLayout(PanelTituloLayout);
        PanelTituloLayout.setHorizontalGroup(
            PanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelTituloLayout.setVerticalGroup(
            PanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        contenedor.setLayout(new java.awt.CardLayout());

        botonProyectos.setText("Proyectos");
        botonProyectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonProyectosActionPerformed(evt);
            }
        });

        botonIngenieros.setText("Ingenieros");

        botonRecursos.setText("Recursos");

        botonSalir.setText("Salir");

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonRecursos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonProyectos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonIngenieros, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                    .addComponent(botonSalir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(532, 532, 532))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonProyectos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonIngenieros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonRecursos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 356, Short.MAX_VALUE)
                .addComponent(botonSalir)
                .addContainerGap())
        );

        contenedor.add(panelMenu, "card2");

        panelProyectos.setLayout(new java.awt.CardLayout());

        tablaProyectos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Descripcion", "Tipo", "Inicio", "Fin", "Presupuesto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scrollTablaProyectos.setViewportView(tablaProyectos);
        if (tablaProyectos.getColumnModel().getColumnCount() > 0) {
            tablaProyectos.getColumnModel().getColumn(1).setPreferredWidth(100);
        }

        botonVolverAlMenu.setText("Volver Al Menu");
        botonVolverAlMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverAlMenuActionPerformed(evt);
            }
        });

        botonAgregarProyecto.setText("Agregar");
        botonAgregarProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarProyectoActionPerformed(evt);
            }
        });

        botonModificarProyecto.setText("Modificar");
        botonModificarProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarProyectoActionPerformed(evt);
            }
        });

        botonEliminarProyecto.setText("Eliminar");

        textCantProyectos.setText("Cantidad de proyectos: NA");

        textCantProyectosHardware.setText("+Hardware: NA");

        textCantProyectosSoftware.setText("+Software: NA");

        javax.swing.GroupLayout subpanelPrincipalProyectosLayout = new javax.swing.GroupLayout(subpanelPrincipalProyectos);
        subpanelPrincipalProyectos.setLayout(subpanelPrincipalProyectosLayout);
        subpanelPrincipalProyectosLayout.setHorizontalGroup(
            subpanelPrincipalProyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 784, Short.MAX_VALUE)
            .addGroup(subpanelPrincipalProyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(subpanelPrincipalProyectosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(subpanelPrincipalProyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(subpanelPrincipalProyectosLayout.createSequentialGroup()
                            .addComponent(botonVolverAlMenu)
                            .addGap(588, 588, 588))
                        .addComponent(scrollTablaProyectos)
                        .addGroup(subpanelPrincipalProyectosLayout.createSequentialGroup()
                            .addComponent(botonAgregarProyecto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(botonModificarProyecto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(botonEliminarProyecto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(subpanelPrincipalProyectosLayout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(textCantProyectos)
                            .addGap(18, 18, 18)
                            .addComponent(textCantProyectosHardware)
                            .addGap(18, 18, 18)
                            .addComponent(textCantProyectosSoftware)
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        subpanelPrincipalProyectosLayout.setVerticalGroup(
            subpanelPrincipalProyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
            .addGroup(subpanelPrincipalProyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(subpanelPrincipalProyectosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(scrollTablaProyectos, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(subpanelPrincipalProyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textCantProyectos)
                        .addComponent(textCantProyectosHardware)
                        .addComponent(textCantProyectosSoftware))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(subpanelPrincipalProyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(botonAgregarProyecto)
                        .addComponent(botonModificarProyecto)
                        .addComponent(botonEliminarProyecto))
                    .addGap(19, 19, 19)
                    .addComponent(botonVolverAlMenu)
                    .addContainerGap()))
        );

        panelProyectos.add(subpanelPrincipalProyectos, "card3");

        campoProyectoTitulo.setText("Título del Proyecto");
        campoProyectoTitulo.setToolTipText("Título del Proyecto");
        campoProyectoTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoProyectoTituloMouseClicked(evt);
            }
        });
        campoProyectoTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoProyectoTituloActionPerformed(evt);
            }
        });

        campoProyectoDescripcion.setText("Descripcion...");
        campoProyectoDescripcion.setToolTipText("Descripcion del Proyecto");
        campoProyectoDescripcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoProyectoDescripcionMouseClicked(evt);
            }
        });

        campoProyectoTipo.setText("Tipo");
        campoProyectoTipo.setToolTipText("Tipo del proyecto");

        spinnerProyectoPresupuesto.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 1.0f));

        spinnerFechaInicio.setModel(new javax.swing.SpinnerDateModel());

        spinnerFechaFin.setModel(new javax.swing.SpinnerDateModel());

        radioHardware.setText("Hardware");
        radioHardware.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioHardwareActionPerformed(evt);
            }
        });

        radioSoftware.setText("Software");
        radioSoftware.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSoftwareActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Presupuesto");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Fecha de inicio");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Fecha de finalizacion");

        botonCargarProyecto.setText("Cargar Proyecto");

        botonVolverPanelPrincipalProyectos.setText("Volver");
        botonVolverPanelPrincipalProyectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverPanelPrincipalProyectosActionPerformed(evt);
            }
        });

        jButton2.setText("Quitar");

        jButton1.setText("Agregar");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Especialidad", "Contratacion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Especialidad", "Contratacion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable3);

        jLabel4.setText("Ingenieros Disponibles:");

        jLabel5.setText("Ingenieros Asignados:");

        jButton3.setText("Recursos");

        jLabel6.setText("pop up? o continuar con un panel dedicado a agregar recursos??");

        javax.swing.GroupLayout subpanelCargarProyectoLayout = new javax.swing.GroupLayout(subpanelCargarProyecto);
        subpanelCargarProyecto.setLayout(subpanelCargarProyectoLayout);
        subpanelCargarProyectoLayout.setHorizontalGroup(
            subpanelCargarProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subpanelCargarProyectoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(subpanelCargarProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonCargarProyecto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonVolverPanelPrincipalProyectos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subpanelCargarProyectoLayout.createSequentialGroup()
                        .addGroup(subpanelCargarProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subpanelCargarProyectoLayout.createSequentialGroup()
                                .addGroup(subpanelCargarProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(subpanelCargarProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spinnerFechaInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spinnerProyectoPresupuesto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spinnerFechaFin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(campoProyectoTipo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subpanelCargarProyectoLayout.createSequentialGroup()
                                .addComponent(campoProyectoTitulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radioHardware)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radioSoftware))
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(subpanelCargarProyectoLayout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(campoProyectoDescripcion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(subpanelCargarProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(subpanelCargarProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subpanelCargarProyectoLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(16, 16, 16)))))
                .addContainerGap())
        );
        subpanelCargarProyectoLayout.setVerticalGroup(
            subpanelCargarProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subpanelCargarProyectoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(subpanelCargarProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoProyectoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioHardware)
                    .addComponent(radioSoftware))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoProyectoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(subpanelCargarProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoProyectoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(subpanelCargarProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(subpanelCargarProyectoLayout.createSequentialGroup()
                        .addGroup(subpanelCargarProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinnerProyectoPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(subpanelCargarProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinnerFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(subpanelCargarProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinnerFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(subpanelCargarProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(subpanelCargarProyectoLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(subpanelCargarProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(botonCargarProyecto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonVolverPanelPrincipalProyectos)
                .addGap(18, 18, 18))
        );

        spinnerProyectoPresupuesto.getAccessibleContext().setAccessibleName("");
        spinnerProyectoPresupuesto.getAccessibleContext().setAccessibleDescription("Presupuesto del proyecto");

        panelProyectos.add(subpanelCargarProyecto, "card2");

        campoProyectoTitulo1.setToolTipText("Título del Proyecto");
        campoProyectoTitulo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoProyectoTitulo1MouseClicked(evt);
            }
        });
        campoProyectoTitulo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoProyectoTitulo1ActionPerformed(evt);
            }
        });

        campoProyectoDescripcion1.setToolTipText("Descripcion del Proyecto");
        campoProyectoDescripcion1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoProyectoDescripcion1MouseClicked(evt);
            }
        });

        campoProyectoTipo1.setToolTipText("Tipo del proyecto");

        spinnerProyectoPresupuesto1.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 1.0f));

        spinnerProyectoFechaInicio1.setModel(new javax.swing.SpinnerDateModel());

        spinnerProyectoFechaFin1.setModel(new javax.swing.SpinnerDateModel());

        radioHardware1.setText("Hardware");
        radioHardware1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioHardware1ActionPerformed(evt);
            }
        });

        radioSoftware1.setText("Software");
        radioSoftware1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSoftware1ActionPerformed(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Presupuesto");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Fecha de inicio");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Fecha de finalizacion");

        botonCargarProyecto1.setText("Modificar Proyecto");

        botonVolverPanelPrincipalProyectos1.setText("Volver");
        botonVolverPanelPrincipalProyectos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverPanelPrincipalProyectos1ActionPerformed(evt);
            }
        });

        jButton4.setText("Quitar");

        jButton5.setText("Agregar");

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Especialidad", "Contratacion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTable4);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Especialidad", "Contratacion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(jTable5);

        jLabel10.setText("Ingenieros Disponibles:");

        jLabel11.setText("Ingenieros Asignados:");

        jButton6.setText("Recursos");

        jLabel12.setText("pop up? o continuar con un panel dedicado a agregar recursos??");

        javax.swing.GroupLayout subpanelModProyectosLayout = new javax.swing.GroupLayout(subpanelModProyectos);
        subpanelModProyectos.setLayout(subpanelModProyectosLayout);
        subpanelModProyectosLayout.setHorizontalGroup(
            subpanelModProyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subpanelModProyectosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(subpanelModProyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonCargarProyecto1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonVolverPanelPrincipalProyectos1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subpanelModProyectosLayout.createSequentialGroup()
                        .addGroup(subpanelModProyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subpanelModProyectosLayout.createSequentialGroup()
                                .addGroup(subpanelModProyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(subpanelModProyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spinnerProyectoFechaInicio1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spinnerProyectoPresupuesto1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spinnerProyectoFechaFin1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(campoProyectoTipo1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subpanelModProyectosLayout.createSequentialGroup()
                                .addComponent(campoProyectoTitulo1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radioHardware1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radioSoftware1))
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(subpanelModProyectosLayout.createSequentialGroup()
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(campoProyectoDescripcion1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(subpanelModProyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(subpanelModProyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subpanelModProyectosLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(16, 16, 16)))))
                .addContainerGap())
        );
        subpanelModProyectosLayout.setVerticalGroup(
            subpanelModProyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subpanelModProyectosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(subpanelModProyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoProyectoTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioHardware1)
                    .addComponent(radioSoftware1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoProyectoDescripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(subpanelModProyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoProyectoTipo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(subpanelModProyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(subpanelModProyectosLayout.createSequentialGroup()
                        .addGroup(subpanelModProyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinnerProyectoPresupuesto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(subpanelModProyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinnerProyectoFechaInicio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(subpanelModProyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinnerProyectoFechaFin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(subpanelModProyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(subpanelModProyectosLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(subpanelModProyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addComponent(botonCargarProyecto1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonVolverPanelPrincipalProyectos1)
                .addGap(18, 18, 18))
        );

        panelProyectos.add(subpanelModProyectos, "card4");

        contenedor.add(panelProyectos, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverAlMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverAlMenuActionPerformed
        textTitulo.setText("MENU PRINCIPAL");
        contenedor.removeAll();
        contenedor.add(panelMenu);
        contenedor.repaint();
        contenedor.revalidate();

        botonVolverAlMenu.setVisible(false);
    }//GEN-LAST:event_botonVolverAlMenuActionPerformed

    private void botonAgregarProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarProyectoActionPerformed
        panelProyectos.removeAll();
        textTitulo.setText("CARGA PROYECTOS");
        panelProyectos.add(subpanelCargarProyecto);
        panelProyectos.repaint();
        panelProyectos.revalidate();
    }//GEN-LAST:event_botonAgregarProyectoActionPerformed

    private void botonProyectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonProyectosActionPerformed

        botonVolverAlMenu.setVisible(true);

        modeloTablaProyectos.setRowCount(0);

        for (int i = 0; i < arrayProyectos.size(); i++) {

            modeloTablaProyectos.addRow(
                    new Object[]{
                        arrayProyectos.get(i).getTitulo(),
                        arrayProyectos.get(i).getTipo(),
                        arrayProyectos.get(i).getDescripcion(),
                        arrayProyectos.get(i).getFechaInicio(),
                        arrayProyectos.get(i).getFechaFin(),
                        arrayProyectos.get(i).getPresupuesto()
                    }
            );

        }
        textTitulo.setText("PROYECTOS");
        textCantProyectos.setText("Cantidad de proyectos: " + modeloTablaProyectos.getRowCount());
        textCantProyectosHardware.setText("+Hardware: " + DesarrolloDeHardware.getCantidadProyHardware());
        textCantProyectosSoftware.setText("+Software: " + DesarrolloDeSoftware.getCantidadProySoftware());

        contenedor.removeAll();
        contenedor.add(panelProyectos);
        contenedor.repaint();
        contenedor.revalidate();
    }//GEN-LAST:event_botonProyectosActionPerformed

    private void radioSoftwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSoftwareActionPerformed
        campoProyectoTipo.setText("Tipo de Aplicacion");
    }//GEN-LAST:event_radioSoftwareActionPerformed

    private void radioHardwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioHardwareActionPerformed
        campoProyectoTipo.setText("Tipo de Dispositivo");
    }//GEN-LAST:event_radioHardwareActionPerformed

    private void botonVolverPanelPrincipalProyectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverPanelPrincipalProyectosActionPerformed

        botonProyectosActionPerformed(evt);
        panelProyectos.remove(subpanelCargarProyecto);
        panelProyectos.add(subpanelPrincipalProyectos);
        contenedor.repaint();
        contenedor.revalidate();
    }//GEN-LAST:event_botonVolverPanelPrincipalProyectosActionPerformed

    private void campoProyectoTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoProyectoTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoProyectoTituloActionPerformed

    private void campoProyectoTituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoProyectoTituloMouseClicked
        campoProyectoTitulo.selectAll();
    }//GEN-LAST:event_campoProyectoTituloMouseClicked

    private void campoProyectoDescripcionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoProyectoDescripcionMouseClicked
        campoProyectoDescripcion.selectAll();

    }//GEN-LAST:event_campoProyectoDescripcionMouseClicked

    private void campoProyectoTitulo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoProyectoTitulo1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_campoProyectoTitulo1MouseClicked

    private void campoProyectoTitulo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoProyectoTitulo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoProyectoTitulo1ActionPerformed

    private void campoProyectoDescripcion1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoProyectoDescripcion1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_campoProyectoDescripcion1MouseClicked

    private void radioHardware1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioHardware1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioHardware1ActionPerformed

    private void radioSoftware1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSoftware1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioSoftware1ActionPerformed

    private void botonVolverPanelPrincipalProyectos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverPanelPrincipalProyectos1ActionPerformed
        botonProyectosActionPerformed(evt);
        panelProyectos.remove(subpanelModProyectos);
        panelProyectos.add(subpanelPrincipalProyectos);
        contenedor.repaint();
        contenedor.revalidate();
    }//GEN-LAST:event_botonVolverPanelPrincipalProyectos1ActionPerformed

    private void botonModificarProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarProyectoActionPerformed
        if (tablaProyectos.getSelectedRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Por favor, seleccione un proyecto de la tabla.");
        } else {
           
            int filaSeleccionada = tablaProyectos.getSelectedRow(), indice=0;    
            String titulo = (String) tablaProyectos.getValueAt(filaSeleccionada, 0);

            for (int i = 0; i < arrayProyectos.size(); i++) {
                if (arrayProyectos.get(i).getTitulo().equals(titulo)) {
                    indice = i;
                }
            }

            campoProyectoTitulo1.setText(arrayProyectos.get(indice).getTitulo());
            campoProyectoDescripcion1.setText(arrayProyectos.get(indice).getDescripcion());
            campoProyectoTipo1.setText(arrayProyectos.get(indice).getTipo());
            campoProyectoTipo1.setText(arrayProyectos.get(indice).getTipo());
            spinnerProyectoPresupuesto1.setValue(arrayProyectos.get(indice).getPresupuesto());
            //spinnerProyectoFechaInicio1.setValue(arrayProyectos.get(indice).getFechaInicio()); error formato de las fechas
            //spinnerProyectoFechaFin1.setValue(arrayProyectos.get(indice).getFechaFin());
            
            //copiar ingenieros y recursos
            
            panelProyectos.removeAll();
            panelProyectos.add(subpanelModProyectos);
            contenedor.repaint();
            contenedor.revalidate();

        }
    }//GEN-LAST:event_botonModificarProyectoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
         */
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelTitulo;
    private javax.swing.JButton botonAgregarProyecto;
    private javax.swing.JButton botonCargarProyecto;
    private javax.swing.JButton botonCargarProyecto1;
    private javax.swing.JButton botonEliminarProyecto;
    private javax.swing.JButton botonIngenieros;
    private javax.swing.JButton botonModificarProyecto;
    private javax.swing.JButton botonProyectos;
    private javax.swing.JButton botonRecursos;
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton botonVolverAlMenu;
    private javax.swing.JButton botonVolverPanelPrincipalProyectos;
    private javax.swing.JButton botonVolverPanelPrincipalProyectos1;
    private javax.swing.ButtonGroup buttonGroupTipoProyecto;
    private javax.swing.JTextField campoProyectoDescripcion;
    private javax.swing.JTextField campoProyectoDescripcion1;
    private javax.swing.JTextField campoProyectoTipo;
    private javax.swing.JTextField campoProyectoTipo1;
    private javax.swing.JTextField campoProyectoTitulo;
    private javax.swing.JTextField campoProyectoTitulo1;
    private javax.swing.JPanel contenedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelProyectos;
    private javax.swing.JRadioButton radioHardware;
    private javax.swing.JRadioButton radioHardware1;
    private javax.swing.JRadioButton radioSoftware;
    private javax.swing.JRadioButton radioSoftware1;
    private javax.swing.JScrollPane scrollTablaProyectos;
    private javax.swing.JSpinner spinnerFechaFin;
    private javax.swing.JSpinner spinnerFechaInicio;
    private javax.swing.JSpinner spinnerProyectoFechaFin1;
    private javax.swing.JSpinner spinnerProyectoFechaInicio1;
    private javax.swing.JSpinner spinnerProyectoPresupuesto;
    private javax.swing.JSpinner spinnerProyectoPresupuesto1;
    private javax.swing.JPanel subpanelCargarProyecto;
    private javax.swing.JPanel subpanelModProyectos;
    private javax.swing.JPanel subpanelPrincipalProyectos;
    private javax.swing.JTable tablaProyectos;
    private javax.swing.JLabel textCantProyectos;
    private javax.swing.JLabel textCantProyectosHardware;
    private javax.swing.JLabel textCantProyectosSoftware;
    private javax.swing.JLabel textTitulo;
    // End of variables declaration//GEN-END:variables
}
